name: Build CLI
on: [push]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.16.3'
    - run: env GOOS=darwin GOARCH=amd64 go build -o pulu-macos . 
    - run: env GOOS=linux GOARCH=amd64 go build -o pulu-linux .
    - run: env GOOS=windows GOARCH=amd64 go build -o pulu-windows .
    - uses: ncipollo/release-action@v1
      with:
        artifacts: pulu-*
        token: ${{ github.token }}
        allowUpdates: true
        prerelease: true
        tag: v0.0.0