name: Build CLI
on: [push]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.16.3'
    - run: go build pulu.go
    - uses: ncipollo/release-action@v1
      with:
        artifacts: 'pulu'
        token: ${{ github.token }}
        allowUpdates: true
        prerelease: true
        tag: v0.0.0